### ISSUE TITLE
Allow to access typed arrays by reference instead of copy

### ISSUE THREAD

**Issue by letmaik** [torch2424/as-bind#47]
Returning a typed array from AS to JS seems to make a copy of it. However, I'd like to obtain a view on the same underlying ArrayBuffer.  Looks like `.slice()` is responsible for the copy: https://github.com/torch2424/as-bind/blob/9ab3ece19866cf8681b9c9d447d37354bfbe7929/lib/asbind-instance/supported-ref-types.js#L29

**Comment by torch2424** [comment]
Ah! Thanks for bringing this up. Yeah currently we are copying because of the context in: #9 

But looking at https://github.com/AssemblyScript/assemblyscript/pull/1047. I'm not too sure if this would introduce breaking changes. 

cc @MaxGraey , do you happen to know if the removing these `.slice()` calls would be safe to use `__getXXArrayView`? :thinking:

**Comment by torch2424** [comment]
Also, I don't want to slow you down @letmaik , if your comfortable, AsBind essentially wraps around the [AS loader](https://www.assemblyscript.org/loader.html#loader), and makes it more convenient. I don't know what project you are working on, but if you don't mind getting a bit more lower level with passing types around, feel free to check that out as well because then you can choose between copying vs getting a direct view :smile:

**Comment by MaxGraey** [comment]
`__getXXArrayView` just create view representation to some range in linear memory. So it's really cheap and don't copy any data, but it unsafe due to array buffer (`memory.buffer`) may detached after any other call from assemblyscript side which use heap, so much better copy it. That's what do `__getXXArray` functions. Its just the same as `__getXXArrayView(...).slice()`. You could use `__getXXArrayView` but you should totally understand what happening on AS side during lifetime of  `__getXXArrayView` instance.

**Comment by MaxGraey** [comment]
```ts
wasmExports.__getInt8Array(responseRef).slice(); 
```

This redundant. It should be just `wasmExports.__getInt8Array()` or `wasmExports.__getInt8ArrayView(responseRef).slice()`

**Comment by letmaik** [comment]
> I don't know what project you are working on (would be super interested to hear if that's okay! No worries if not! 😄 ), but if you don't mind getting a bit more lower level with passing types around, feel free to check that out as well because then you can choose between copying vs getting a direct view 😄

This is for a hobby project, basically my first emulator (for a simple system to start with, CHIP-8), and I'd like to use AS because it seems really nice :) So there's definitely no urgency here but I'd like to do it the proper way as if it was a performance-critical piece of code, while also staying as high-level as possible. That's why I'm looking at as-bind to remove the nasty details at the boundary.

> `__getXXArrayView` just create view representation to some region of linear memory based on pointer which comes from AS. So it's really cheap and don't copy any data, but it's also unsafe due to array buffer (`memory.buffer`) may detached after any other call from assemblyscript side which use heap [...]

I'd like to understand this a bit better. As long as the typed array object exists in wasm memory, it is safe to use it in JS, right? Or is there a case where an existing object can get relocated to a different location in linear memory?

**Comment by MaxGraey** [comment]
> As long as the typed array object exists in wasm memory, it is safe to use it in JS, right? 

using `__getXXArrayView` for long lifetime defenitely unsafe, but if you have something like this:
```ts
const arrPtr = wasm.someProcessing();
let typedArray = __getUint8ArrayView(arrPtr);

pureJSProcessing(typedArray);  // don't call any methods from wasm

__release(arrPtr); // free resource
```
It could work properly.

But if `pureJSProcessing` for example call some other or the same wasm method which could potentially alloc or dealloc memory in heap it may cause to detouched arraybuffer or invalid data associated to this arraybuffer.

I hope this is clearer now =)

**Comment by letmaik** [comment]
I found a description of the same issue here: https://github.com/emscripten-core/emscripten/issues/6747

I think as-bind should allow to get an unsafe view on array buffers. This could be opt-in by setting some config option similar to the type caching option:

```js
asBindInstance.exports.myFunction.returnUnsafeArrayViews = true; // default false
// or globally:
asBindInstance.returnUnsafeArrayViews = true;
```

The docs should mention that by default a copy is returned, but advanced users can opt in to get a view instead, together with all the caveats, e.g. the array buffer must still be alive/referenced inside wasm (since the reference count will not be increased when returning the buffer), and no further wasm function should be invoked (to avoid triggering memory growth which would detach the view).

**Comment by torch2424** [comment]
@MaxGraey 

> This redundant. It should be just wasmExports.__getInt8Array(responseRef) or wasmExports.__getInt8ArrayView(responseRef).slice() which is basically the same.

Ah for sure! Thanks for catching that! Yeah I remember we used to need it for some reason :thinking: 

> using __getXXArrayView for long lifetime defenitely unsafe

Thank you for clarifying! Yeah I remember bumping into this a while back, but then we fixed it in the loader :smile:

---

@letmaik 

> This is for a hobby project, basically my first emulator 

Oh nice! Yeah emulators are fun! That's super awesome! :smile: :tada: 

> I think as-bind should allow to get an unsafe view on array buffers. This could be opt-in by setting some config option similar to the type caching option:

Yeah, so we can totally add this option on functions, I think it'd work! Though, I'll probably think of a different name. Probably like `unsafeReturnValue`. Since, in the future maybe we will have a `getStringUnsafe`, or `getClassUnsafe` etc... in the loader. Also, if we can ever pass an unsafe parameter (unlikely), we could name it `unsafeParams` or something :smile: 

The change mostly needs to be done here: https://github.com/torch2424/as-bind/blob/master/lib/asbind-instance/supported-ref-types.js#L127

Providing an `getUnsafeValueFromRef`. And then upadating this block: https://github.com/torch2424/as-bind/blob/master/lib/asbind-instance/bind-function.js#L229

Actually, that's super easy. I'll just do that now :joy: GIve me like 10 minutes :smile:

**Comment by torch2424** [comment]
@letmaik 

Should be live in `0.4.1` :smile: Docs are there on the README on how to use it :smile: :tada:

**Comment by letmaik** [comment]
@torch2424 Great! Just out of curiosity, why does it return the ptr and the array? What can you do with the ptr?

**Comment by torch2424** [comment]
@letmaik Yay! Glad it's working for you!

I returned them both for a few reasons:

1. So it is more obvious that it's returning the unsafe version. I figured it'd be a lot easier to debug if the flag got set somewhere by accident, and then someone else calls the function, expecting it to copy.

2. Since you have bi-directional view into Wasm memory, if you want to modify the array, it'd maybe be helpful to know where the array is, or you could wrap in a different typed array.

3. Itd be alot easier to test this for both me, and consumers of the API 😀

I was hoenstly a bit 50/50 if it should return the pointer. But I figured more good than harm could come from it 😀
