### ISSUE TITLE
u16 buggy

### ISSUE THREAD

**Issue by letmaik** [torch2424/as-bind#50]
I got a function that I want to export:
```ts
export function foo(): u16 {
..
}
```
If I access that function directly through unboundExports it works, but through as-bind it tries to interpret it as a string for some reason: `Uncaught Error: not a string: 516`.

u8 is working btw.

**Comment by torch2424** [comment]
@letmaik Do you happen to know what the returned value is? :thinking: Or is it `516`? 

Maybe it's possible the value you are returning just happens to serendipitously match up with a string in memory?

cc @MaxGraey , do you happen to know if returned values can happened to be interpreted as pointers by the loader? :thinking:

**Comment by MaxGraey** [comment]
> do you happen to know if returned values can happened to be interpreted as pointers by the loader?

Loader never try to guessing types. If you call `exports.foo()` it return number, if you wrap it to `exports.__getString(exports.foo())` loader will interpret returned version of `foo` as pointer. In WebAssembly all passing values if actually doubles (f64), and we haven't any tagged values something like this. `loader` is just collection of glue functions + name demangling.

**Comment by letmaik** [comment]
@torch2424 The value that's supposed to be returned is 516.

**Comment by torch2424** [comment]
@MaxGraey 

Ah! My apologies, I guess I am referring to the runtimes `__instanceof` perhaps than: https://github.com/torch2424/as-bind/blob/master/lib/asbind-instance/supported-ref-types.js#L14 .

On second thought, this probably is possible because if you happen to have a string allocated at that pointer being returned, than this could return true @MaxGraey ? :thinking: 

If so, I'll update the docs to suggest using the `unboundExports` for number types. :smile: 

---

@letmaik Awesome! Thanks for the insight!

**Comment by MaxGraey** [comment]
> Ah! My apologies, I guess I am referring to the runtimes __instanceof perhaps than: https://github.com/torch2424/as-bind/blob/master/lib/asbind-instance/supported-ref-types.js#L14 .

Now I see. So yes, in this case it could be false positive determined as string. For example `foo(): u16` in theory may return same number as pointer of some string in memory. So checking this via dynamic `instanceof` has no grantees

**Comment by torch2424** [comment]
@MaxGraey Ahhhh! Well that's not good haha! :joy: 

> When we do this only on AS side most of instanceof checks statically for primitive types at least and there we can't have such issues

Could you point me to where this is done? Since we have the as-bind entryfile, I could probably do some type of hinting hopefully, or provide some type of import so that they can hint on the AS side what is being returned. 

Otherwise, I think I can introduce a "force type" function or something. Which I think would make the API less clean. But! Since we are already working on the bindings generator, I'd be okay with it, since this is meant to be replaced by that anyways :smile:

**Comment by MaxGraey** [comment]
> Could you point me to where this is done? Since we have the as-bind entryfile, I could probably do some type of hinting hopefully, or provide some type of import so that they can hint on the AS side what is being returned.

It's better ask to @dcodeIO

**Comment by dcodeIO** [comment]
The compiler knows the types of each value flowing around and only accesses the managed object header, and the runtime id within, when it knows that something is a managed object. That's about what `isManaged<T>()` checks for. I guess ideally we'd go into the direction of some sort of as-bindgen, generating JS glue code utilizing the type information the compiler has.

**Comment by torch2424** [comment]
Thanks for the insight @MaxGraey @dcodeIO :smile: 

Cool, in the meantime while we work on the as-bindgen thing, I'll go ahead and allow forcing a type :smile: 

Probably will do something like:

`asBindInstance.exports.myExportedFunction.returnType = AsBind.TYPES.NUMBER`

:smile: :+1:

**Comment by torch2424** [comment]
Fixed and published in `0.5.0` :smile: 

Like I mentioned, I added a `returnType` property for forcing the return type for bound export functions, and then recommended it's usage for production applications :smile:
